image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  variables:
    PUBLIC_URL: https://2022.igem.wiki/teccem

  script:
    - npm install
    - npm install -g svgo
    - CI=false npm run build
    - rm -rf public
    - mv out public
    - cp build/index.html build/404.html
    - mv build public

  artifacts:
    paths:
      - public
  only:
    - main
